### ISSUE TITLE
Need a script for Google classroom

### ISSUE THREAD

**Issue by sakthi19sk** [jeryjs/Userscripts#1]
Can you please make a Script code for changing Class name in Google classroom

**Comment by jeryjs** [comment]
Sure, I'll start working on the script sometime tomorrow.

**Comment by jeryjs** [comment]
@sakthi19sk 
The script is ready.
If you have a userscript manager installed, you can directly install it by clicking here- https://github.com/jeryjs/Userscripts/raw/main/Google-Classroom_Edit-Course-Names.user.js
